[package]
name = "lit"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4", features = ["derive"] }
color-eyre = "0.6"
markdown = "1.0.0-alpha"
tracing-subscriber = "0.3"
walkdir = "2"
